language: node_js
node_js:
  - '13'
  - '12'
  - '10'
matrix:
  include:
    - node_js: '12'
      env: INTEGRATION=true
script:
  - if [[ $INTEGRATION == true ]]; then npm run integration; fi
before_install: npm install --global npm
after_success:
  - if [[ $INTEGRATION != true ]]; then npx codecov --file=./coverage/lcov.info; fi
